kinematic_plugins:
  search_paths:
    - /home/gmruser/deps/tesseract_ws/install/tesseract_kinematics/lib
  search_libraries:
    - tesseract_kinematics_kdl_factories
  fwd_kin_plugins:
    arm:
      default: KDLFwdKinChain
      plugins:
        KDLFwdKinChain:
          class: KDLFwdKinChainFactory
          config:
            base_link: y_prismatic
            tip_link: tool0
  inv_kin_plugins:
    arm:
      default: KDLInvKinChainLMA
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: y_prismatic
            tip_link: tool0